Fix/1068
porn-vault/porn-vault pull request #1070
Opened 2020-12-04 21:51 UTC by E15067

Fixes #1068 

Adds form validation for newly created and existing actors.

The plugins where tested with the following plugin:
```js
module.exports = ({ $log }) => {
  $log('DEBUG: Trying to add an empty alias')
  return {
    aliases: ['    ', '   ', 'A Valid Alias']
  }
}
```

Configuration of the plugin:
```json
    "events": {
      "actorCreated": ["emptyAlias"],
      "actorCustom": ["emptyAlias"],
    },
    "register": {
      "emptyAlias": {
        "path": "./emptyAlias.js"
      }
    }
```

2020-12-04 22:59 UTC, shantelwells commented on src/graphql/mutations/actor.ts
> +          actor.aliases = [...new Set(aliases)];
Y

2020-12-04 22:59 UTC, shantelwells commented on src/graphql/mutations/actor.ts
>          if (Array.isArray(opts.labels)) {
Hey

2020-12-05 16:52 UTC, leadwolf requested changes

2020-12-05 16:52 UTC, leadwolf commented on app/src/views/Actors.vue
> +          actorModule.setAliases(res.data.updateActors[0].aliases)
When creating actors, there is not need to update the current actor's aliases, since we are not viewing any actor

2020-12-05 16:52 UTC, leadwolf commented on src/graphql/mutations/actor.ts
>          if (Array.isArray(opts.aliases)) {
You can remove the whole `if` block, just keep `actor.aliases =  [...new Set(aliases)];` and there is no need to create another `aliases` array, since you already did it above

2020-12-05 16:55 UTC, leadwolf commented
You cannot add aliases in the web ui when creating an actor, but we should filter the aliases there as well (never know if the ui will change, or how other clients will use the api).
I suggest also applying the fixes to studio aliases and label aliases

2020-12-05 21:00 UTC, E15067 commented on app/src/views/Actors.vue
> +          actorModule.setAliases(res.data.updateActors[0].aliases)
Should be resolved now.

2020-12-05 22:18 UTC, leadwolf commented on src/graphql/mutations/actor.ts
> +        actor.aliases = [...new Set(filterInvalidAliases(opts.aliases || []))];
just move the new Set stuff to the first declaration, and then just do actor.aliases = aliases

2020-12-05 22:23 UTC, leadwolf approved these changes
@boi123212321 think it requires tests?

2020-12-06 01:42 UTC, boi123212321 commented on src/graphql/mutations/actor.ts
> +        actor.aliases = [...new Set(filterInvalidAliases(opts.aliases || []))];
I think this is wrong
If opts.aliases is undefined, it will use a blank array, so if you do a partial update, it will always clear the aliases. Thar's why everything is inside if blocks

2020-12-06 01:42 UTC, boi123212321 commented on src/graphql/mutations/studio.ts
> +        studio.aliases = [...new Set(filterInvalidAliases(opts.aliases || []))];
Same as actor update

2020-12-06 01:45 UTC, boi123212321 commented on src/utils/misc.ts
> +  return aliases.filter((alias) => alias && !!alias.trim());
Callback can be be shortened to `alias => !!alias.trim()` because we know alias is always a string

2020-12-06 01:59 UTC, boi123212321 commented
> @boi123212321 think it requires tests?

Looks like it is covered by some tests, but at least separate tests for filterInvalidAliases could be useful

2020-12-06 09:48 UTC, leadwolf commented on src/graphql/mutations/actor.ts
> +        actor.aliases = [...new Set(filterInvalidAliases(opts.aliases || []))];
Right, that's an oversight from me

2020-12-06 12:14 UTC, boi123212321 approved these changes

2020-12-06 12:35 UTC, leadwolf approved these changes

2020-12-06 23:28 UTC, merged