Add page number to route `/scenes`
porn-vault/porn-vault pull request #1113
Opened 2020-12-16 10:06 UTC by themese8

Adds the page number to  `/scenes` route, and handles history state, so you can go back / link to specific pages.

Closes #1087

2020-12-17 15:07 UTC, boi123212321 commented
Good one, but this should happen for all listings (actors, movies, studios, images, (markers))

2020-12-17 15:08 UTC, boi123212321 requested changes
Add page parameter to other listings as well

2020-12-20 14:33 UTC, leadwolf commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
should stick to using vue-router
```suggestion
        this.$router.push(`/scenes/${page.toString()}`);
```

2020-12-21 08:15 UTC, themese8 commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
Yes and no. `$router.push` is different than `history.pushState`

https://router.vuejs.org/guide/essentials/navigation.html#router-push-location-oncomplete-onabort

`$router.push` actually navigates to the new url, but all I want is to update the url in the url bar. I couldn't find similar method in `$router`.

2020-12-21 08:50 UTC, leadwolf commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
But we do want to navigate, that way you can press back in the browser, it will change the pagination.  
I realize that it wasn't included in the original description but it seems logical to me. It also requires watching the route, to react to update the search according to the route change. I guess it should be another issue ?

But even then, $router.push and history.pushState should be the same, since vue-router is in hash mode. What difference are you thinking of ?

2020-12-22 06:27 UTC, themese8 commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
history.pushState just pushes new state to history, so you can press back in the browser. $router.push pushes new state AND triggers router change in $router.

2020-12-22 10:02 UTC, leadwolf commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
But what's bad about that?

2020-12-23 08:30 UTC, themese8 commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
It creates an infinite loop, where it tries to load the new page infinitely.

2020-12-27 13:30 UTC, boi123212321 commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
I guess $router is the better solution, but using history may be a intermediate solution for now

2021-01-07 09:04 UTC, themese8 commented on app/src/views/Scenes.vue
> +        history.pushState({}, "", "#/scenes/" + page.toString());
After taking a look at the code again, you are right @leadwolf, it's better to use the router for actual navigation. I'll need to rework this functionality.

2021-02-07 16:10 UTC, boi123212321 commented
Continued in https://github.com/porn-vault/porn-vault/pull/1224

2021-02-07 16:10 UTC, closed without merging