add actors multi selection, delete selection and bulk run plugins
porn-vault/porn-vault pull request #1137
Opened 2020-12-27 14:08 UTC by not-wolfgang

- [ [actors multi selection](https://imgur.com/a/LBYQ580)] 
- [ [delete selection / run plugin on selection](https://imgur.com/a/MbxKKZs)] 
- [ [run plugins for all actors](https://imgur.com/a/MIx7tVR)]

2021-01-08 15:33 UTC, leadwolf requested changes

2021-01-08 15:33 UTC, leadwolf commented on app/src/components/Cards/Actor.vue
> -      <a :href="`#/actor/${value._id}`">
you shouldn't remove the link otherwise the user cannot middle click to open the actor in a new tab

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +      color="deep-purple accent-4"
is there any reason for it to be purple instead of the theme default ?

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +            >Run plugins for selected actors</v-btn
Nitpicking, but "for selected actors is redundant"

```suggestion
            >Run plugins</v-btn
```

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +            class="text-none"
Show the button loading, while plugins are being run

```suggestion
            class="text-none"
            :loading="pluginLoader"
```

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +      .catch((err) => {
If the actor is currently being displayed, we should update that actor's data with the result

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +      <v-card>
Create a `deleteSelectionLoader` bool, activate it when running the delete mutation (and use it in other areas, see other comments)

```suggestion
      <v-card :loading="deleteSelectionLoader">
```

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +          <v-btn class="text-none" color="error" text @click="deleteSelection">Delete</v-btn>
Show the button :loading here as well

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +            v-if="selectedActors.length"
add a loading state to the button (see other comments)

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +            <v-btn v-on="on" @click="runPluginsForAllActors" icon>
add loading state to the button

2021-01-08 15:33 UTC, leadwolf commented on app/src/views/Actors.vue
> +  async runPluginsForAllActors() {
I don't know if iterating on all the actors from the ui is a good idea.
For example, if you close the tab, it'll interrupt the process.
@boi123212321 thoughts ?

2021-01-08 15:34 UTC, leadwolf commented on app/src/views/Actors.vue
> +    if (forceSelectionChange || event.ctrlKey) {
should handle shift click like on the images page

2021-01-10 14:05 UTC, boi123212321 commented on app/src/views/Actors.vue
> +  async runPluginsForAllActors() {
I think it's fine as long as some loading/progress is shown

2021-01-19 16:16 UTC, boi123212321 requested changes
See leadwolf's requests

2021-01-19 16:18 UTC, leadwolf commented on app/src/views/Actors.vue
> +      <v-card>
In practice, it might not be necessary if the deletion is so fast that we wouldn't even see the loader. I don't know how fast actor deletion is though

2021-03-23 19:13 UTC, leadwolf commented
Replaced by #1348 because of inactivity (your work is preserved)

2021-03-23 19:13 UTC, closed without merging