(refactor) Search query format
porn-vault/porn-vault pull request #824
Opened 2020-09-26 23:28 UTC by boi123212321

2020-09-28 20:16 UTC, leadwolf requested changes

2020-09-28 20:16 UTC, leadwolf commented on src/search/actor.ts
> +    skip: options.skip || (options.page || 0) * 24,
when there's no skip, wouldn't it be `skip: options.skip || (options.page || 0) * (options.take || PAGE_SIZE)` ?

2020-09-28 20:16 UTC, leadwolf commented on src/search/actor.ts
> +  // const options = extractQueryOptions(query);
useless comment?

2020-09-28 20:16 UTC, leadwolf commented on src/search/image.ts
> +    skip: options.skip || (options.page || 0) * 24,
same thing about the skip calculation

2020-09-28 20:16 UTC, leadwolf commented on src/search/movie.ts
> +    skip: options.skip || (options.page || 0) * 24,
same thing about skip calculation

2020-09-28 20:16 UTC, leadwolf commented on src/search/scene.ts
> +    skip: options.skip || (options.page || 0) * 24,
same thing about skip calculation

2020-09-28 20:16 UTC, leadwolf commented on src/search/studio.ts
> +    skip: options.skip || (options.page || 0) * 24,
same thing about skip calculation

2020-09-29 22:03 UTC, boi123212321 commented on app/src/views/Studios.vue
>    @Watch("ratingFilter", {})
Yeah that should go... copy paste mistake

2020-09-30 15:10 UTC, boi123212321 commented
TODO markers search

2020-10-09 21:43 UTC, leadwolf approved these changes

2020-10-09 22:29 UTC, merged